version: '3.2'
services:
  client-dev: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - HOST:0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: .
        target: /home/node/app
  client-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./src
        target: /home/node/app/src

